(cl:defpackage donkey_service-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "DEGREEDATA"
   "<DEGREEDATA-REQUEST>"
   "DEGREEDATA-REQUEST"
   "<DEGREEDATA-RESPONSE>"
   "DEGREEDATA-RESPONSE"
   "DISTANCEDATA"
   "<DISTANCEDATA-REQUEST>"
   "DISTANCEDATA-REQUEST"
   "<DISTANCEDATA-RESPONSE>"
   "DISTANCEDATA-RESPONSE"
  ))

