// Generated by gencpp from file donkey_service/AddTwoInts.msg
// DO NOT EDIT!


#ifndef DONKEY_SERVICE_MESSAGE_ADDTWOINTS_H
#define DONKEY_SERVICE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <donkey_service/AddTwoIntsRequest.h>
#include <donkey_service/AddTwoIntsResponse.h>


namespace donkey_service
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace donkey_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::donkey_service::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::donkey_service::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::donkey_service::AddTwoInts > {
  static const char* value()
  {
    return "donkey_service/AddTwoInts";
  }

  static const char* value(const ::donkey_service::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::donkey_service::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::donkey_service::AddTwoInts >
template<>
struct MD5Sum< ::donkey_service::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::donkey_service::AddTwoInts >::value();
  }
  static const char* value(const ::donkey_service::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::donkey_service::AddTwoIntsRequest> should match
// service_traits::DataType< ::donkey_service::AddTwoInts >
template<>
struct DataType< ::donkey_service::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::donkey_service::AddTwoInts >::value();
  }
  static const char* value(const ::donkey_service::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::donkey_service::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::donkey_service::AddTwoInts >
template<>
struct MD5Sum< ::donkey_service::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::donkey_service::AddTwoInts >::value();
  }
  static const char* value(const ::donkey_service::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::donkey_service::AddTwoIntsResponse> should match
// service_traits::DataType< ::donkey_service::AddTwoInts >
template<>
struct DataType< ::donkey_service::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::donkey_service::AddTwoInts >::value();
  }
  static const char* value(const ::donkey_service::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DONKEY_SERVICE_MESSAGE_ADDTWOINTS_H
