// Generated by gencpp from file donkey_service/DistanceDataRequest.msg
// DO NOT EDIT!


#ifndef DONKEY_SERVICE_MESSAGE_DISTANCEDATAREQUEST_H
#define DONKEY_SERVICE_MESSAGE_DISTANCEDATAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace donkey_service
{
template <class ContainerAllocator>
struct DistanceDataRequest_
{
  typedef DistanceDataRequest_<ContainerAllocator> Type;

  DistanceDataRequest_()
    : dataresponse(0)  {
    }
  DistanceDataRequest_(const ContainerAllocator& _alloc)
    : dataresponse(0)  {
  (void)_alloc;
    }



   typedef int8_t _dataresponse_type;
  _dataresponse_type dataresponse;





  typedef boost::shared_ptr< ::donkey_service::DistanceDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::donkey_service::DistanceDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DistanceDataRequest_

typedef ::donkey_service::DistanceDataRequest_<std::allocator<void> > DistanceDataRequest;

typedef boost::shared_ptr< ::donkey_service::DistanceDataRequest > DistanceDataRequestPtr;
typedef boost::shared_ptr< ::donkey_service::DistanceDataRequest const> DistanceDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::donkey_service::DistanceDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::donkey_service::DistanceDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::donkey_service::DistanceDataRequest_<ContainerAllocator1> & lhs, const ::donkey_service::DistanceDataRequest_<ContainerAllocator2> & rhs)
{
  return lhs.dataresponse == rhs.dataresponse;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::donkey_service::DistanceDataRequest_<ContainerAllocator1> & lhs, const ::donkey_service::DistanceDataRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace donkey_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::donkey_service::DistanceDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::donkey_service::DistanceDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::donkey_service::DistanceDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::donkey_service::DistanceDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::donkey_service::DistanceDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::donkey_service::DistanceDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::donkey_service::DistanceDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4d21e51ccccd78f0f83658973688752";
  }

  static const char* value(const ::donkey_service::DistanceDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4d21e51ccccd78fULL;
  static const uint64_t static_value2 = 0x0f83658973688752ULL;
};

template<class ContainerAllocator>
struct DataType< ::donkey_service::DistanceDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "donkey_service/DistanceDataRequest";
  }

  static const char* value(const ::donkey_service::DistanceDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::donkey_service::DistanceDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# request params\n"
"byte dataresponse\n"
;
  }

  static const char* value(const ::donkey_service::DistanceDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::donkey_service::DistanceDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dataresponse);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DistanceDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::donkey_service::DistanceDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::donkey_service::DistanceDataRequest_<ContainerAllocator>& v)
  {
    s << indent << "dataresponse: ";
    Printer<int8_t>::stream(s, indent + "  ", v.dataresponse);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DONKEY_SERVICE_MESSAGE_DISTANCEDATAREQUEST_H
