// Generated by gencpp from file donkey_service/DistanceData.msg
// DO NOT EDIT!


#ifndef DONKEY_SERVICE_MESSAGE_DISTANCEDATA_H
#define DONKEY_SERVICE_MESSAGE_DISTANCEDATA_H

#include <ros/service_traits.h>


#include <donkey_service/DistanceDataRequest.h>
#include <donkey_service/DistanceDataResponse.h>


namespace donkey_service
{

struct DistanceData
{

typedef DistanceDataRequest Request;
typedef DistanceDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DistanceData
} // namespace donkey_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::donkey_service::DistanceData > {
  static const char* value()
  {
    return "89951c538fe0bce2d7e1746ebb68223c";
  }

  static const char* value(const ::donkey_service::DistanceData&) { return value(); }
};

template<>
struct DataType< ::donkey_service::DistanceData > {
  static const char* value()
  {
    return "donkey_service/DistanceData";
  }

  static const char* value(const ::donkey_service::DistanceData&) { return value(); }
};


// service_traits::MD5Sum< ::donkey_service::DistanceDataRequest> should match
// service_traits::MD5Sum< ::donkey_service::DistanceData >
template<>
struct MD5Sum< ::donkey_service::DistanceDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::donkey_service::DistanceData >::value();
  }
  static const char* value(const ::donkey_service::DistanceDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::donkey_service::DistanceDataRequest> should match
// service_traits::DataType< ::donkey_service::DistanceData >
template<>
struct DataType< ::donkey_service::DistanceDataRequest>
{
  static const char* value()
  {
    return DataType< ::donkey_service::DistanceData >::value();
  }
  static const char* value(const ::donkey_service::DistanceDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::donkey_service::DistanceDataResponse> should match
// service_traits::MD5Sum< ::donkey_service::DistanceData >
template<>
struct MD5Sum< ::donkey_service::DistanceDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::donkey_service::DistanceData >::value();
  }
  static const char* value(const ::donkey_service::DistanceDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::donkey_service::DistanceDataResponse> should match
// service_traits::DataType< ::donkey_service::DistanceData >
template<>
struct DataType< ::donkey_service::DistanceDataResponse>
{
  static const char* value()
  {
    return DataType< ::donkey_service::DistanceData >::value();
  }
  static const char* value(const ::donkey_service::DistanceDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DONKEY_SERVICE_MESSAGE_DISTANCEDATA_H
