// Generated by gencpp from file acc_urban_service/YoloDataResponse.msg
// DO NOT EDIT!


#ifndef ACC_URBAN_SERVICE_MESSAGE_YOLODATARESPONSE_H
#define ACC_URBAN_SERVICE_MESSAGE_YOLODATARESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace acc_urban_service
{
template <class ContainerAllocator>
struct YoloDataResponse_
{
  typedef YoloDataResponse_<ContainerAllocator> Type;

  YoloDataResponse_()
    : datarequest(0)  {
    }
  YoloDataResponse_(const ContainerAllocator& _alloc)
    : datarequest(0)  {
  (void)_alloc;
    }



   typedef int8_t _datarequest_type;
  _datarequest_type datarequest;





  typedef boost::shared_ptr< ::acc_urban_service::YoloDataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acc_urban_service::YoloDataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct YoloDataResponse_

typedef ::acc_urban_service::YoloDataResponse_<std::allocator<void> > YoloDataResponse;

typedef boost::shared_ptr< ::acc_urban_service::YoloDataResponse > YoloDataResponsePtr;
typedef boost::shared_ptr< ::acc_urban_service::YoloDataResponse const> YoloDataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acc_urban_service::YoloDataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acc_urban_service::YoloDataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acc_urban_service::YoloDataResponse_<ContainerAllocator1> & lhs, const ::acc_urban_service::YoloDataResponse_<ContainerAllocator2> & rhs)
{
  return lhs.datarequest == rhs.datarequest;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acc_urban_service::YoloDataResponse_<ContainerAllocator1> & lhs, const ::acc_urban_service::YoloDataResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acc_urban_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acc_urban_service::YoloDataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acc_urban_service::YoloDataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acc_urban_service::YoloDataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acc_urban_service::YoloDataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acc_urban_service::YoloDataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acc_urban_service::YoloDataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acc_urban_service::YoloDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b80a56dcde916e60c3c82cddd4361019";
  }

  static const char* value(const ::acc_urban_service::YoloDataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb80a56dcde916e60ULL;
  static const uint64_t static_value2 = 0xc3c82cddd4361019ULL;
};

template<class ContainerAllocator>
struct DataType< ::acc_urban_service::YoloDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acc_urban_service/YoloDataResponse";
  }

  static const char* value(const ::acc_urban_service::YoloDataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acc_urban_service::YoloDataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 datarequest\n"
"\n"
;
  }

  static const char* value(const ::acc_urban_service::YoloDataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acc_urban_service::YoloDataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.datarequest);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YoloDataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acc_urban_service::YoloDataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acc_urban_service::YoloDataResponse_<ContainerAllocator>& v)
  {
    s << indent << "datarequest: ";
    Printer<int8_t>::stream(s, indent + "  ", v.datarequest);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACC_URBAN_SERVICE_MESSAGE_YOLODATARESPONSE_H
